project_id = "dsvmigyunbwdefibbpgm"

[functions.allocate-job]
verify_jwt = true

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-reminder-email]
verify_jwt = false

[functions.handle-job-response]
verify_jwt = true

[functions.get-job-tracking]
verify_jwt = false